# Generated by Django 3.0.6 on 2020-05-06 12:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('otp_twilio', '0003_longer_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twiliosmsdevice',
            name='key',
        ),
        migrations.RemoveField(
            model_name='twiliosmsdevice',
            name='last_t',
        ),
        migrations.AddField(
            model_name='twiliosmsdevice',
            name='throttling_failure_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of successive failed attempts.'),
        ),
        migrations.AddField(
            model_name='twiliosmsdevice',
            name='throttling_failure_timestamp',
            field=models.DateTimeField(blank=True, default=None, help_text='A timestamp of the last failed verification attempt. Null if last attempt succeeded.', null=True),
        ),
        migrations.AddField(
            model_name='twiliosmsdevice',
            name='token',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='twiliosmsdevice',
            name='valid_until',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The timestamp of the moment of expiry of the saved token.'),
        ),
    ]
