name: Run tests

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: |
            3.8
            3.10
            3.12

      - name: Install hatch
        run: pipx install hatch

      - name: Run tests
        run: hatch run test:run

      - name: Build docs
        run: hatch run docs:make
